# -*- coding: utf-8 -*-
"""Cópia de PROJETO 01 - JOGO DA FORCA EM PYTHON  - VERSÃO 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bu5dJ-1PPnA5RfkSUZef8P6zoAnlqpTJ

##PROJETO 01 - DESEVOLVER UM GAME EM LINGUAGEM PYTHON
#PSEUDOCODIGO

1 - DEFINIR A LISTA DE PALAVRAS POSSÍVEIS

2 - ESCOLHER UMA PALAVRA ALEATÓRIA DA LISTA

3 - CRIAR UMA LISTA VAZIA PARA ARMAZENAR AS LETRAS

4 - DEFINIR O NUMERO MÁXIMO DE TENTATIVAS PERMITIDAS

5 -  ENQUANTO O NUMERO MAXIMO DE TENTAIVAS NÃO ATINGIR O LIMITE MAXIMO ;
- MOSTRAR A PALAVRA COMO UMA SERIE DE UNDERSCORES ( _ ), COM AS LETRAS ADIVINHADAS PREENCHENDO OS ESPAÇOS CORRETOS
- PEDIR AO JOGADOR QUE ADIVINHE UMA LETRA
- VERIFICAR SE A LETRA ADIVINHADA ESTA NA PALAVRA
- SE A LETRA ADIVINHADA ESTA NA PALAVRA, ADICIONAR A LETRA DE LISTAS ADIVINHADAS E ATUALIZAR A EXIBIÇÃO DAS PALAVRAS
- SE A LETRA ADIVINHADA NÃO ESTA NA PALAVRA, REDUZIR O NUMERO DE TENTATIVAS RESTANTES A EXIBIR A MENSAGEM 'LETRA INCORRETA'. TENTATIVAS RESTANTES [ NUMERO DE TENTATIVAS RESTANTES]
- VERIFICAR SE TODAS AS LETRAS DA PALAVRA FORAM ADIVINHADAS
- SE TODAS AS LETRAS FORAM ADIVINHADAS, EXIBIR A MENSAVEM ' VOCE VENCEU !!! '
- SE O NUMERO DE TENTATIVAS RESTANTES CHEGAR A ZERO, EXIBIR A MENSAGEM '' VOCE PERDEU '' A PALAVRA ESCOLHIDAS ERA '' E ENCERAR O JOGO
"""

#IMPORT
import random
from os import system, name

# Projeto 1 - Desenvolvimento de Game em Linguagem Python - Versão 1

# Import
import random
from os import system, name

# Função para limar a tela a cada execução
def limpa_tela():

    # Windows
    if name == 'nt':
        _ = system('cls')

    # Mac ou Linux
    else:
        _ = system('clear')

# Função
def game():

    limpa_tela()
    print("\nBem-vindo(a) ao jogo da forca!")
    print("Adivinhe a palavra abaixo:\n")

    # Lista de palavras para o jogo
    palavras = ['banana', 'abacate', 'uva', 'morango', 'laranja']

    # Escolhe randomicamente uma palavra
    palavra = random.choice(palavras)

    # List comprehension
    letras_descobertas = ['_' for letra in palavra]

    # Número de chances
    chances = 6

    # Lista para as letras erradas
    letras_erradas = []

    # Loop enquanto número de chances for maior do que zero
    while chances > 0:

        # Print
        print(" ".join(letras_descobertas))
        print("\nChances restantes:", chances)
        print("Letras erradas:", " ".join(letras_erradas))

        # Tentativa
        tentativa = input("\nDigite uma letra: ").lower()

        # Condicional
        if tentativa in palavra:
            index = 0
            for letra in palavra:
                if tentativa == letra:
                    letras_descobertas[index] = letra
                index += 1
        else:
            chances -= 1
            letras_erradas.append(tentativa)

        # Condicional
        if "_" not in letras_descobertas:
            print("\nVocê venceu, a palavra era:", palavra)
            break

    # Condicional
    if "_" in letras_descobertas:
        print("\nVocê perdeu, a palavra era:", palavra)

# Bloco main
if __name__ == "__main__":
    game()
    print("\nParabéns. Você está aprendendo programação em Python. :)\n")

